---
title: Cass Elliott
timezone: America/Los_Angeles
collections:
  painting:
    title: Painting
    output: true
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
  sculpture:
    title: Sculpture
    output: true
  uploads:
    title: Uploads
    output: true
email: dev@adriandiaz.ca
description: Cass Elliott's artist portfolio
baseurl: 
url: 
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
