---
title: Cass Elliott
timezone: UTC
collections:
  painting:
    title: Painting
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: dev@adriandiaz.ca
description: Cass Elliott's artist portfolio
baseurl: ''
url: ''
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
